spring:
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true

  data:
    mongodb:
      host: transactions-mongo-db
      port: 27017
      database: transactions-staging

server:
  port: 8080