spring:
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true

  data:
    mongodb:
      host: localhost
      port: 27017
      database: transactions-dev
      uri: mongodb://localhost:27017/transactions-dev

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/auth/realms/transactions
          jwk-set-uri: http://localhost:8082/auth/realms/transactions/protocol/openid-connect/certs

server:
  port: 8080