spring:
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true

  data:
    mongodb:
      host: transactions-mongo-db
      port: 27017
      database: transactions-staging
      uri: mongodb://transactions-mongo-db:27017/transactions-staging

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/transactions
          jwk-set-uri: http://keycloak:8080/auth/realms/transactions/protocol/openid-connect/certs

server:
  port: 8080