name: transactions-java-server-external-apps
services:
  mongo6:
    container_name: dev-transactions-mongo-db-6
    image: mongo:6.0.7
    ports:
      - "27018:27017"

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin-slim:latest
    ports:
      - "9411:9411"