include:
  - docker-compose-dev-postgresql.yml

services:
  transactions-app-docker:
    container_name: transactions-app-docker
    build:
      dockerfile: Dockerfile
      context: ../../
    env_file: "app.env"
    ports:
      - "8080:8080"
    volumes:
      - ./config:/etc/config