name: transactions-java CI - PUBLISH DOCKER IMAGE

on:
  release:
    types: [published]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download last package
        uses: actions/download-artifact@v1
        with:
          name: package
          path: ./api/target/
      - name: Build image
        run: docker build . --file Dockerfile --tag image

